apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nodejs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moshedana058/sample-nodejs.git
    targetRevision: main
    path: charts/sample-nodejs
    helm:
      releaseName: sample-nodejs
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-nodejs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

