apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-nodejs.fullname" . }}
  labels:
    {{- include "sample-nodejs.labels" . | nindent 4 }}
data:
  APP_GREETING: {{ .Values.config.appGreeting | quote }}
