name: CI Pipeline - Sample NodeJS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: itamarchn/sample-nodejs
  GITOPS_REPO: itamarchn7/sample-nodejs-gitops
  VALUES_FILE: helm/values.yaml
  BASE_VERSION: '1.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout code
      - name: Checkout application repo
        uses: actions/checkout@v4

      # 2 SAST – Static Application Security Testing
      - name: SAST - Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/nodejs
        env:
          SEMGREP_FAIL_ON_SEVERITY: ERROR

      # 3 Calculate version
      - name: Calculate SemVer
        id: version
        run: |          
          PATCH=${{ github.run_number }}
          echo "IMAGE_TAG=${BASE_VERSION}.${PATCH}" >> $GITHUB_ENV

      # 4 Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${IMAGE_TAG} .

      # 5 Scan Docker image for vulnerabilities
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          exit-code: 1

      # 6 Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      # 7 Push Docker image
      - name: Push Docker image
        run: docker push $IMAGE_NAME:${IMAGE_TAG}

      # 8 Update GitOps repository
      - name: Update GitOps repo with new image tag
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITOPS_REPO}.git gitops
          cd gitops

          sed -i 's/tag: .*/tag: "'${IMAGE_TAG}'"/' $VALUES_FILE

          git config user.email "ci@github-actions"
          git config user.name "github-actions"

          git add $VALUES_FILE
          git commit -m "Update image tag to ${IMAGE_TAG}"
          git push
