name: CI Pipeline - Sample NodeJS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: itamarchn/sample-nodejs
  GITOPS_REPO: itamarchn7/sample-nodejs-gitops
  VALUES_FILE: helm/values.yaml
  BASE_VERSION: '1.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸ Checkout code
      - name: Checkout application repo
        uses: actions/checkout@v4

      # 2 Calculate version
      - name: Calculate SemVer
        id: version
        run: |          
          PATCH=${{ github.run_number }}
          echo "IMAGE_TAG=${BASE_VERSION}.${PATCH}" >> $GITHUB_ENV

      # 3 Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${IMAGE_TAG} .

      # 4 Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 5 Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${IMAGE_TAG}

      # 6 Update GitOps repository
      - name: Update GitOps repo with new image tag
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITOPS_REPO}.git gitops
          cd gitops

          sed -i 's/tag: .*/tag: "${IMAGE_TAG}"/' $VALUES_FILE

          git config user.email "ci@github-actions"
          git config user.name "github-actions"

          git add $VALUES_FILE
          git commit -m "Update image tag to ${IMAGE_TAG}"
          git push
